// levelpack — a HOST build tool. Reads a plain-text level map and emits a C++
// header embedding it as a string literal. This is the "code generation" step:
// it must run on the BUILD HOST, even when the game itself is cross-compiled
// (e.g. to WebAssembly) — you can't run a .wasm during a Linux build.
//
// PROVIDED. Usage: levelpack <input.txt> <output.hpp>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

int main(int argc, char** argv) {
    if (argc != 3) {
        std::cerr << "usage: levelpack <input.txt> <output.hpp>\n";
        return 1;
    }

    std::ifstream in(argv[1]);
    if (!in) {
        std::cerr << "levelpack: cannot open " << argv[1] << '\n';
        return 1;
    }

    // The output path lives under the build tree (e.g. generated/dungeon/), and
    // CMake does not create a custom command's output directory for us, so make it.
    const std::filesystem::path outPath(argv[2]);
    if (outPath.has_parent_path()) {
        std::filesystem::create_directories(outPath.parent_path());
    }

    std::ofstream out(outPath);
    if (!out) {
        std::cerr << "levelpack: cannot write " << argv[2] << '\n';
        return 1;
    }

    out << "// Generated by levelpack — do not edit.\n"
           "#pragma once\n"
           "namespace dungeon {\n"
           "inline constexpr const char* kIntroLevel =\n";

    std::string line;
    while (std::getline(in, line)) {
        out << '"';
        for (const char c : line) {
            if (c == '\\' || c == '"') out << '\\';
            out << c;
        }
        out << "\\n\"\n";
    }

    out << ";\n} // namespace dungeon\n";
    return 0;
}
